<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Beneficiary;
use App\Models\SppgUnit;

class BeneficiarySeeder extends Seeder
{
    public function run(): void
    {
        $sppgUnits = SppgUnit::pluck('id_sppg_unit')->toArray();

        $beneficiaries = [
            [
                'id_sppg_unit' => $sppgUnits[0] ?? null,
                'group_type' => 'Sekolah',
                'category' => 'SD',
                'code' => 'SDN01',
                'name' => 'SDN 01 Buleleng',
                'ownership_type' => 'Negeri',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Buleleng',
                'village' => 'Kampung Baru',
                'address' => 'Jl. Pahlawan No. 1',
                'postal_code' => '81111',
                'latitude_gps' => -8.112345,
                'longitude_gps' => 115.091234,
                'small_portion_male' => 50,
                'small_portion_female' => 45,
                'large_portion_male' => 0,
                'large_portion_female' => 0,
                'teacher_portion' => 10,
                'staff_portion' => 5,
                'cadre_portion' => 0,
                'pic_name' => 'Budi',
                'pic_phone' => '08123456789',
                'pic_email' => 'budi@example.com',
                'is_active' => true,
            ],
            [
                'id_sppg_unit' => $sppgUnits[1] ?? null,
                'group_type' => 'Posyandu',
                'category' => 'Posyandu Balita',
                'code' => 'POS02',
                'name' => 'Posyandu Mawar',
                'ownership_type' => 'Masyarakat',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Sukasada',
                'village' => 'Sambangan',
                'address' => 'Jl. Raya Sambangan',
                'postal_code' => '81161',
                'latitude_gps' => -8.145678,
                'longitude_gps' => 115.101234,
                'small_portion_male' => 20,
                'small_portion_female' => 25,
                'large_portion_male' => 0,
                'large_portion_female' => 0,
                'teacher_portion' => 0,
                'staff_portion' => 0,
                'cadre_portion' => 5,
                'pic_name' => 'Siti',
                'pic_phone' => '08765432109',
                'pic_email' => 'siti@example.com',
                'is_active' => true,
            ],
            [
                'id_sppg_unit' => $sppgUnits[2] ?? null,
                'group_type' => 'Sekolah',
                'category' => 'SMP',
                'code' => 'SMP03',
                'name' => 'SMPN 02 Singaraja',
                'ownership_type' => 'Negeri',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Buleleng',
                'village' => 'Banjar Jawa',
                'address' => 'Jl. Ngurah Rai No. 5',
                'postal_code' => '81113',
                'latitude_gps' => -8.123456,
                'longitude_gps' => 115.087654,
                'small_portion_male' => 0,
                'small_portion_female' => 0,
                'large_portion_male' => 120,
                'large_portion_female' => 115,
                'teacher_portion' => 25,
                'staff_portion' => 10,
                'cadre_portion' => 0,
                'pic_name' => 'Agus',
                'pic_phone' => '081222333444',
                'pic_email' => 'agus@example.com',
                'is_active' => true,
            ],
            [
                'id_sppg_unit' => $sppgUnits[3] ?? null,
                'group_type' => 'Posyandu',
                'category' => 'Posyandu Lansia',
                'code' => 'POS04',
                'name' => 'Posyandu Melati',
                'ownership_type' => 'Desa',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Banjar',
                'village' => 'Dencarik',
                'address' => 'Jl. Seririt-Singaraja',
                'postal_code' => '81152',
                'latitude_gps' => -8.187654,
                'longitude_gps' => 115.012345,
                'small_portion_male' => 15,
                'small_portion_female' => 20,
                'large_portion_male' => 0,
                'large_portion_female' => 0,
                'teacher_portion' => 0,
                'staff_portion' => 0,
                'cadre_portion' => 8,
                'pic_name' => 'Dewi',
                'pic_phone' => '081333444555',
                'pic_email' => 'dewi@example.com',
                'is_active' => true,
            ],
            [
                'id_sppg_unit' => $sppgUnits[4] ?? null,
                'group_type' => 'Kelompok Lainnya',
                'category' => 'Yayasan',
                'code' => 'YYS05',
                'name' => 'Yayasan Kasih Ibu',
                'ownership_type' => 'Swasta',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Buleleng',
                'village' => 'Pemaron',
                'address' => 'Jl. Sudirman No. 10',
                'postal_code' => '81116',
                'latitude_gps' => -8.134567,
                'longitude_gps' => 115.067890,
                'small_portion_male' => 30,
                'small_portion_female' => 30,
                'large_portion_male' => 0,
                'large_portion_female' => 0,
                'teacher_portion' => 5,
                'staff_portion' => 5,
                'cadre_portion' => 0,
                'pic_name' => 'Wayan',
                'pic_phone' => '081555666777',
                'pic_email' => 'wayan@example.com',
                'is_active' => true,
            ],
        ];

        foreach ($beneficiaries as $beneficiary) {
            Beneficiary::create($beneficiary);
        }
    }
}
