<?php

namespace Database\Seeders;

use App\Models\SppgUnit;
use Illuminate\Database\Seeder;

class SppgUnitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $units = [
            [
                'id_sppg_unit' => '2DWFSVHQ',
                'code_sppg_unit' => '51.08.04.2014.01',
                'name' => 'SPPG Buleleng Banjar Dencarik',
                'status' => 'Operasional',
                'operational_date' => '2025-05-19',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Banjar',
                'village' => 'Dencarik',
                'address' => 'Jalan Seririt - Singaraja (Sebelah Barat SPBU Dencarik) Br Corot, Ds Dencarik , Kec Banjar, Kab Buleleng, Bali (81152)',
                'latitude_gps' => -8.1864444,
                'longitude_gps' => 114.9765556,
                'leader_id' => null,
                'nutritionist_id' => null,
                'accountant_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => '59QMIA7P',
                'code_sppg_unit' => '51.08.05.2001.01',
                'name' => 'SPPG Buleleng Sukasada Pancasari',
                'status' => 'Operasional',
                'operational_date' => '2025-08-19',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Sukasada',
                'village' => 'Pancasari',
                'address' => 'Jalan Singaraja–Denpasar KM 4, Lingkar Sangket, Kecamatan Sukasada, Kabupaten Buleleng, Bali',
                'latitude_gps' => -8.1543611,
                'longitude_gps' => 115.1081944,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'RQCH6R1P',
                'code_sppg_unit' => '51.08.04.2015.02',
                'name' => 'SPPG Buleleng Banjar Temukus',
                'status' => 'Operasional',
                'operational_date' => '2025-08-19',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Banjar',
                'village' => 'Temukus',
                'address' => 'Jalan Seririt-Singaraja, Desa Temukus, Banjar Dinas Pegayaman, Kecamatan Banjar, Kabupaten Buleleng, Bali',
                'latitude_gps' => -8.184119437,
                'longitude_gps' => 114.9832623,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'ML77EUWD',
                'code_sppg_unit' => '51.08.03.2011.01',
                'name' => 'SPPG Buleleng Busungbiu Busungbiu',
                'status' => 'Operasional',
                'operational_date' => '2025-08-19',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Busungbiu',
                'village' => 'Busungbiu',
                'address' => 'Banjar Dinas Kelod, Kilometer 0,5, Desa Busungbiu, Kecamatan Busungbiu',
                'latitude_gps' => -8.255856,
                'longitude_gps' => 114.96379,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'GEVFSFKQ',
                'code_sppg_unit' => '51.08.02.1015.02',
                'name' => 'SPPG Buleleng Seririt Seririt',
                'status' => 'Operasional',
                'operational_date' => '2025-08-21',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Seririt',
                'village' => 'Seririt',
                'address' => 'Jl. Diponegoro No. 106 Kelurahan Seririt, Kecamatan Seririt, Kabupaten Buleleng, BaliL',
                'latitude_gps' => -8.193314,
                'longitude_gps' => 114.9265801,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'WEF8P627',
                'code_sppg_unit' => '51.08.06.1024.01',
                'name' => 'SPPG Buleleng Buleleng Kaliuntu',
                'status' => 'Operasional',
                'operational_date' => '2025-08-25',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Buleleng',
                'village' => 'Kaliuntu',
                'address' => 'Jalan Jatayu No 15 A, Kaliuntu Singaraja, Buleleng, Kab. BULELENG',
                'latitude_gps' => -8.1097744,
                'longitude_gps' => 115.080771,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'FUAGRV0J',
                'code_sppg_unit' => '51.08.06.2004.02',
                'name' => 'SPPG Buleleng Buleleng Pemaron',
                'status' => 'Operasional',
                'operational_date' => '2025-08-25',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Buleleng',
                'village' => 'Pemaron',
                'address' => 'Banjar Dinas Dauh Margi, Desa Pemaron, Buleleng, Kab. Buleleng, Bali',
                'latitude_gps' => -8.13576,
                'longitude_gps' => 115.0637167,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'T69YLRI9',
                'code_sppg_unit' => '51.08.02.2017.01',
                'name' => 'SPPG Buleleng Seririt Lokapaksa',
                'status' => 'Operasional',
                'operational_date' => '2025-08-25',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Seririt',
                'village' => 'Lokapaksa',
                'address' => 'Jl. S. Parman, No. 18, Kelurahan Seririt, Kecamatan Seririt, Kabupaten Buleleng, Provinsi Bali',
                'latitude_gps' => -8.1940335,
                'longitude_gps' => 114.9307365,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'VD4GMZI4',
                'code_sppg_unit' => '51.08.09.2008.01',
                'name' => 'SPPG Buleleng Tejakula Penuktukan',
                'status' => 'Operasional',
                'operational_date' => '2025-09-22',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Tejakula',
                'village' => 'Penuktukan',
                'address' => 'Jl. Singaraja-Amlapura, Desa Penuktukan, Kec. Tejakula, Kab. Buleleng',
                'latitude_gps' => -8.14144,
                'longitude_gps' => 115.389671,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => '1ZMXJYKC',
                'code_sppg_unit' => '51.08.06.1025.03',
                'name' => 'SPPG Buleleng Buleleng Kampung Anyar',
                'status' => 'Operasional',
                'operational_date' => '2025-09-22',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Buleleng',
                'village' => 'Kampung Anyar',
                'address' => 'Jl. Merak No. 7B, Kelurahan Kampung Anyar, Kecamatan Buleleng, Kabupaten Buleleng.',
                'latitude_gps' => -8.106827,
                'longitude_gps' => 115.085482,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => '78FEBDFW',
                'code_sppg_unit' => '51.08.09.2006.02',
                'name' => 'SPPG Buleleng Tejakula Tejakula',
                'status' => 'Operasional',
                'operational_date' => '2025-09-29',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Tejakula',
                'village' => 'Tejakula',
                'address' => 'Jl. Air Sanih - Tejakula, Banjar Dinas Suci, Desa Tejakula',
                'latitude_gps' => -8.121508,
                'longitude_gps' => 115.331548,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'X5MVRZ71',
                'code_sppg_unit' => '51.08.06.1019.04',
                'name' => 'SPPG Buleleng Buleleng Banyuning',
                'status' => 'Operasional',
                'operational_date' => '2025-09-29',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Buleleng',
                'village' => 'Banyuning',
                'address' => 'Jl. Pulau Komodo, Perumahan Puri Komodo, Banyuning, Buleleng, Kab. Buleleng, Bali.',
                'latitude_gps' => -8.100770226,
                'longitude_gps' => 115.103454,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => '03IHQELJ',
                'code_sppg_unit' => '51.08.07.2012.01',
                'name' => 'SPPG Buleleng Sawan Sangsit',
                'status' => 'Operasional',
                'operational_date' => '2025-09-29',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Sawan',
                'village' => 'Sangsit',
                'address' => 'Jl. Raya Sangsit, Banjar Dinas Beji, Desa Sangsit, Kecamatan Sawan, Kabupaten Buleleng',
                'latitude_gps' => -8.082185,
                'longitude_gps' => 115.132765,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => '0UFWNQYF',
                'code_sppg_unit' => '51.08.07.2003.02',
                'name' => 'SPPG Buleleng Sawan Sekumpul',
                'status' => 'Operasional',
                'operational_date' => '2025-10-13',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Sawan',
                'village' => 'Sekumpul',
                'address' => 'Banjar Dinas Desa, Desa Sekumpul Kecamatan Sawan, Kabupaten Buleleng, Bali',
                'latitude_gps' => -8.172473,
                'longitude_gps' => 115.185363,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'HOIZFIRD',
                'code_sppg_unit' => '51.08.02.2013.03',
                'name' => 'SPPG Buleleng Seririt Bubunan',
                'status' => 'Operasional',
                'operational_date' => '2025-10-27',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Seririt',
                'village' => 'Bubunan',
                'address' => 'Jalan Raya Seririt Pupuan, Banjar Dinas Tegal Sari, Desa Bubunan, Kecamatan Seririt, Kabupaten Buleleng, Bali',
                'latitude_gps' => -8.2148419,
                'longitude_gps' => 114.9401494,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'MQDLOVUG',
                'code_sppg_unit' => '51.08.02.2014.04',
                'name' => 'SPPG Buleleng Seririt Patemon',
                'status' => 'Operasional',
                'operational_date' => '2025-10-27',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Seririt',
                'village' => 'Patemon',
                'address' => 'Jl. Raya Elang Gang IV, Desa Patemon, Kecamatan Seririt, Kabupaten Buleleng, Bali.',
                'latitude_gps' => -8.1950833,
                'longitude_gps' => 114.925,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'IKY6NI5Z',
                'code_sppg_unit' => '51.08.07.2013.03',
                'name' => 'SPPG Buleleng Sawan Bungkulan',
                'status' => 'Operasional',
                'operational_date' => '2025-11-03',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Sawan',
                'village' => 'Bungkulan',
                'address' => 'Jalan Raya Bungkulan Kecamatan Sawan, Kabupaten Buleleng',
                'latitude_gps' => -8.080625,
                'longitude_gps' => 115.146564,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'K1ZM61RW',
                'code_sppg_unit' => '51.08.05.2010.02',
                'name' => 'SPPG Buleleng Sukasada Sambangan',
                'status' => 'Operasional',
                'operational_date' => '2025-11-10',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Sukasada',
                'village' => 'Sambangan',
                'address' => 'Banjar dinas Babakan, Desa/Kelurahan Sambangan, Kec. Sukasada, Kab.Buleleng, Provinsi Bali',
                'latitude_gps' => -8.1475956,
                'longitude_gps' => 115.0977871,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'JOXDHG8U',
                'code_sppg_unit' => '51.08.01.2003.01',
                'name' => 'SPPG Buleleng Gerokgak Sumberkima',
                'status' => 'Operasional',
                'operational_date' => '2025-11-14',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Gerokgak',
                'village' => 'Sumberkima',
                'address' => 'Jl. Singaraja Gilimanuk, Desa Sumberkima, Kec. Gerokgak, Kab. Buleleng',
                'latitude_gps' => -8.14387,
                'longitude_gps' => 114.620749,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => '5SOJV20U',
                'code_sppg_unit' => '51.08.06.1020.05',
                'name' => 'SPPG Buleleng Buleleng Penarukan',
                'status' => 'Operasional',
                'operational_date' => '2025-11-17',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Buleleng',
                'village' => 'Penarukan',
                'address' => 'JL. Natuna no 24 penarukan , kec. Buleleng, kab. buleleng, bali',
                'latitude_gps' => -8.087232,
                'longitude_gps' => 115.115084,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'BPQUT5T',
                'code_sppg_unit' => '51.08.06.1024.06',
                'name' => 'SPPG Buleleng Buleleng Kaliuntu 2',
                'status' => 'Operasional',
                'operational_date' => '2025-12-08',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Buleleng',
                'village' => 'Kaliuntu',
                'address' => 'Jalan Ahmad Yani, Kelurahan Kaliuntu, Kec. Buleleng, Kab. Buleleng',
                'latitude_gps' => -8.112705,
                'longitude_gps' => 115.084157,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'XW9CR1H5',
                'code_sppg_unit' => '51.08.09.2002.03',
                'name' => 'SPPG Buleleng Tejakula Pacung',
                'status' => 'Operasional',
                'operational_date' => '2025-12-15',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Tejakula',
                'village' => 'Pacung',
                'address' => 'Jalan Air Sanih Tejakula, Banjar Dinas Alas Sari, Desa Pacung, Kec. Tejakula, Kab. Buleleng',
                'latitude_gps' => -8.100074,
                'longitude_gps' => 115.279074,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'RT6X2NDS',
                'code_sppg_unit' => '51.08.07.2014.04',
                'name' => 'SPPG Buleleng Sawan Giri Emas',
                'status' => 'Operasional',
                'operational_date' => '2026-01-12',
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Sawan',
                'village' => 'Giri Emas',
                'address' => 'Jalan Raya Sangsit, Giri Emas, Kecamatan Sawan, Kabupaten Buleleng',
                'latitude_gps' => -8.084605,
                'longitude_gps' => 115.137332,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => 'GOKNX0PX',
                'code_sppg_unit' => '51.08.08.2007.01',
                'name' => 'SPPG Buleleng Kubutambahan Tamblang',
                'status' => 'Belum Operasional',
                'operational_date' => null,
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Kubutambahan',
                'village' => 'Tamblang',
                'address' => 'Tamblang, Kecamatan Kubutambahan, Kabupaten Buleleng, Bali',
                'latitude_gps' => -8.130106,
                'longitude_gps' => 115.196136,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
            [
                'id_sppg_unit' => '0VQG7FCS',
                'code_sppg_unit' => '51.08.03.2011.02',
                'name' => 'SPPG Buleleng Busungbiu Busungbiu 2',
                'status' => 'Belum Operasional',
                'operational_date' => null,
                'province' => 'Bali',
                'regency' => 'Buleleng',
                'district' => 'Busungbiu',
                'village' => 'Busungbiu',
                'address' => 'Desa Busungbiu, Kecamatan Busungbiu, Kabupaten Buleleng',
                'latitude_gps' => -8.257009,
                'longitude_gps' => 114.965973,
                'leader_id' => null,
                'photo' => null,
                'social' => ['facebook_url' => null, 'instagram_url' => null, 'tiktok_url' => null]
            ],
        ];

        foreach ($units as $unitData) {
            $socialData = $unitData['social'];
            unset($unitData['social']);

            $unit = SppgUnit::create($unitData);
            $unit->socialMedia()->create($socialData);
        }
    }
}
